In [1]:
import numpy as np
#ALWAYS import numpy as 'np'

## Indexing

In [2]:
a = np.array([1, 2, 3])
a

#creating a numpy array

array([1, 2, 3])

In [3]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix

#you can make a multi-dimensional array by passing a list of lists 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a[0]

#accessing the first element of array 'a'

1

In [5]:
print('a    == {}'.format(a))
print('a[0] == {}'.format(a[0]))
print('a[1] == {}'.format(a[1]))
print('a[2] == {}'.format(a[2]))

a    == [1 2 3]
a[0] == 1
a[1] == 2
a[2] == 3


In [6]:
matrix[1, 1]

#obtaining the second element in the second arrary 'matrix'

5

In [7]:
matrix[1:, :2]

#obtaining the first 2 elements of the last 2 rows

array([[4, 5],
       [7, 8]])

In [8]:
should_include_elements = [True, False, True]
a[should_include_elements]

#you can use bool values to select elements
##boolean sequence MUST be the same length as array

array([1, 3])

## Vectorized Operations

In [9]:
original_array = [1, 2, 3, 4, 5]
try:
    original_array + 1
except TypeError as e:
    print('An Error Occured!')
    print(f'TypeError: {e}')
    
    #cannot adjust list items

An Error Occured!
TypeError: can only concatenate list (not "int") to list


In [10]:
original_array = [1, 2, 3, 4, 5]
array_with_one_added = []
for n in original_array:
    array_with_one_added.append(n + 1)
print(array_with_one_added)

#create a new array and run items through a for loop to adjust values 

[2, 3, 4, 5, 6]


In [11]:
original_array = [1, 2, 3, 4, 5]
array_with_one_added = [n + 1 for n in original_array]
print(array_with_one_added)

[2, 3, 4, 5, 6]


In [12]:
original_array = np.array([1, 2, 3, 4, 5])
original_array + 1

#using numpy you CAN simply add to the values in an array

array([2, 3, 4, 5, 6])

In [13]:
my_array = np.array([-3, 0, 3, 16])

print('my_array      == {}'.format(my_array))
print('my_array - 5  == {}'.format(my_array - 5))
print('my_array * 4  == {}'.format(my_array * 4))
print('my_array / 2  == {}'.format(my_array / 2))
print('my_array ** 2 == {}'.format(my_array ** 2))
print('my_array % 2  == {}'.format(my_array % 2))

#works for all arithmatic operators 

my_array      == [-3  0  3 16]
my_array - 5  == [-8 -5 -2 11]
my_array * 4  == [-12   0  12  64]
my_array / 2  == [-1.5  0.   1.5  8. ]
my_array ** 2 == [  9   0   9 256]
my_array % 2  == [1 0 1 0]


In [14]:
my_array = np.array([-3, 0, 3, 16])

print('my_array       == {}'.format(my_array))
print('my_array == -3 == {}'.format(my_array == -3))
print('my_array >= 0  == {}'.format(my_array >= 0))
print('my_array < 10  == {}'.format(my_array < 10))

#also works with comparison operators 

my_array       == [-3  0  3 16]
my_array == -3 == [ True False False False]
my_array >= 0  == [False  True  True  True]
my_array < 10  == [ True  True  True False]


In [15]:
my_array[my_array > 0]

#can use comparison operators to find values in an array that meet criteria 

array([ 3, 16])

In [16]:
my_array[my_array % 2 == 0]

array([ 0, 16])

In [17]:
my_array % 2

array([1, 0, 1, 0])

In [18]:
result = my_array % 2
result == 0

array([False,  True, False,  True])

In [19]:
step_1 = my_array % 2
step_2 = step_1 == 0
step_3 = my_array[step_2]

step_3

array([ 0, 16])

In [20]:
print('1. my_array[my_array % 2 == 0]')
print('    - the original expression')
print('2. my_array[{} % 2 == 0]'.format(my_array))
print('    - variable substitution')
print('3. my_array[{} == 0]'.format(my_array % 2))
print('    - result of performing the vectorized modulus 2')
print('4. my_array[{}]'.format(my_array % 2 == 0))
print('    - result of comparing to 0')
print('5. {}[{}]'.format(my_array, my_array % 2 == 0))
print('    - variable substitution')
print('6. {}'.format(my_array[my_array % 2 == 0]))
print('    - our final result')

1. my_array[my_array % 2 == 0]
    - the original expression
2. my_array[[-3  0  3 16] % 2 == 0]
    - variable substitution
3. my_array[[1 0 1 0] == 0]
    - result of performing the vectorized modulus 2
4. my_array[[False  True False  True]]
    - result of comparing to 0
5. [-3  0  3 16][[False  True False  True]]
    - variable substitution
6. [ 0 16]
    - our final result


## Array Creation

In [21]:
np.random.randn(10)

#creates an array of 10 random numbers 

array([ 1.27086653, -0.66332408,  2.15480163,  2.04103133, -1.21287027,
       -1.74213427, -0.01756183, -0.62770474, -1.21005941,  0.04020299])

In [22]:
np.random.randn(3, 4)

#creates a multidimensional array of 3 arrays with 4 random numbers each

array([[-1.73699629,  0.70055345, -0.87719078,  0.22792192],
       [-1.15709984,  0.74455733,  1.36427201, -0.54041636],
       [ 0.73771117,  0.91379915,  0.16693389, -0.30928006]])

In [23]:
mu = 100
sigma = 30

sigma * np.random.randn(20) + mu

array([130.91217422,  83.53726089,  61.26301086, 104.42053828,
        93.79104112,  86.65731818, 141.54233522, 132.28228264,
        91.27711256, 140.78004236,  83.32359893, 143.53548184,
       111.76896583, 110.90613462,  71.21572973, 116.49555747,
       129.80722177,  63.42152841, 139.80965382, 151.31360155])

In [24]:
print('np.zeros(3)    == {}'.format(np.zeros(3)))
#creates an array of 3 0's

print('np.ones(3)     == {}'.format(np.ones(3)))
#creates an array of 3 1's

print('np.full(3, 17) == {}'.format(np.full(3, 17)))
#creats an array of 3 17's

np.zeros(3)    == [0. 0. 0.]
np.ones(3)     == [1. 1. 1.]
np.full(3, 17) == [17 17 17]


In [25]:
np.zeros((2, 3))
#creates a multidimensional array of 2 arrays of 3 0's

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.arange(4)
#numpy arange works similarly to python range
##creates an array of numbers between 0-3

array([0, 1, 2, 3])

In [27]:
np.arange(1, 4)
#array of numbers between 1 and 3

array([1, 2, 3])

In [28]:
np.arange(1, 4, 2)
#array of numbers between 1 and 3, skipping every other number

array([1, 3])

In [29]:
np.arange(3, 5, 0.5)
#can handle decimals 

array([3. , 3.5, 4. , 4.5])

In [30]:
print('min: 1, max: 4, length = 4 -- {}'.format(np.linspace(1, 4, 4)))
#creates an array of numbers between 1 and 4 with 4 elements

print('min: 1, max: 4, length = 7 -- {} '.format(np.linspace(1, 4, 7)))
#creates and array of numbers between 1 and 4 with 7 elements 

min: 1, max: 4, length = 4 -- [1. 2. 3. 4.]
min: 1, max: 4, length = 7 -- [1.  1.5 2.  2.5 3.  3.5 4. ] 


## Array Methods

In [31]:
a = np.array([1, 2, 3, 4, 5])

In [32]:
a.min()
#finds smallest element in array

1

In [33]:
a.max()
#finds largest element in an array

5

In [34]:
a.mean()
#finds mean of all elements in an array

3.0

In [35]:
a.sum()
#finds sum of adding all elements in an array 

15

In [36]:
a.std()
#standard deviation of elements in an array 

1.4142135623730951